# Generated by Django 6.0.1 on 2026-01-24 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=150)),
                ('number_of_book_published', models.IntegerField(default=0, null=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('author_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorVerification',
            fields=[
                ('author_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='author.author')),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
