# Generated by Django 6.0.1 on 2026-01-24 07:29

import author.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublished',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=500)),
                ('book_title', models.CharField()),
                ('book_description', models.CharField()),
                ('book_genres', models.CharField(choices=[('Fiction', 'FICTION'), ('Fantasy', 'FANTASY'), ('Mystery', 'MYSTERY'), ('Romance', 'ROMANCE'), ('Science', 'SCIENCE'), ('Technology', 'TECHNOLOGY'), ('Business', 'BUSINESS'), ('Self-Help', 'SELF-HELP')])),
                ('book_cover_page', models.ImageField(upload_to=author.models.book_path)),
                ('book_pfd', models.FileField(upload_to=author.models.book_pdf_path)),
                ('book_download', models.IntegerField(default=0)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
