# Generated by Django 6.0.1 on 2026-01-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_bookpublished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpublished',
            old_name='book_pfd',
            new_name='book_pdf',
        ),
    ]
