# Generated by Django 6.0.1 on 2026-01-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_booksdownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='verified_by_admin',
        ),
    ]
