# Generated by Django 6.0.1 on 2026-01-30 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_remove_author_verified_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpublished',
            name='book_genres',
            field=models.CharField(choices=[('Fiction', 'FICTION'), ('Fantasy', 'FANTASY'), ('Mystery', 'MYSTERY'), ('Romance', 'ROMANCE'), ('Biography', 'BIOGRAPHY'), ('Technology', 'TECHNOLOGY'), ('Business', 'BUSINESS'), ('Self-Help', 'SELF-HELP')]),
        ),
        migrations.CreateModel(
            name='ResetPwVerification',
            fields=[
                ('pw_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
