# Generated by Django 6.0.1 on 2026-01-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_rename_book_genres_bookpublished_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpublished',
            old_name='book_genre',
            new_name='book_genres',
        ),
    ]
