# Generated by Django 6.0.1 on 2026-01-29 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_like_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPwVerification',
            fields=[
                ('pw_id', models.UUIDField(default=uuid.uuid4)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
            ],
        ),
    ]
