# Generated by Django 6.0.1 on 2026-01-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_rename_book_genres_bookpublished_book_genre'),
        ('user', '0005_alter_user_like_book_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_like_book',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.bookpublished'),
        ),
        migrations.AlterField(
            model_name='user_like_book',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
